In [1]:
import cProfile
import pandas as pd
from src.recovery_model import RecoveryModel
import os

pd.set_option("multi_sparse", False)
pd.set_option("display.float_format", "{:.2f}".format)

## test with 40 flows

In [2]:
folder = "test_1"
path = f"data/{folder}/"
elt = "Ag"
folder_out = f"{folder}_{elt}"

In [3]:
# # original
# inputs = pd.read_csv(path + "inputs.csv")
# composition = pd.read_csv(path + "composition.csv")
# TCs = pd.read_csv(path + "TCs.csv")
# metadata = pd.read_csv(path + "metadata.csv")

# # Remove all but "Ag" element

# sgl_Elt = (composition["element"].isna()) | (composition["element"] == elt)
# composition = composition[sgl_Elt]

# mask = metadata["element"] == elt
# metadata["element"] = None
# metadata.loc[mask, "element"] = elt

# mask1 = (TCs["input_layer"] == "element") & (TCs["input_layer_key"] != elt)
# mask2 = (TCs["output_layer"] == "element") & (TCs["output_target_key"] != elt)
# mask = mask1 | mask2
# TCs = TCs[~mask]

# path_out = f"data/{folder_out}/"
# if not os.path.exists(path_out):
#     os.makedirs(path_out)

# inputs.to_csv(path_out + "inputs.csv", index=False)
# composition.to_csv(path_out + "composition.csv", index=False)
# TCs.to_csv(path_out + "TCs.csv", index=False)
# metadata.to_csv(path_out + "metadata.csv", index=False)

# del metadata, inputs, composition, TCs

In [4]:
# Select a folder for the data to be used
folder = "test_2"  # test_1  test_2  Toy_WEEE_v2 folder_out
layer_0 = "flow"
layer_1 = "product"
layer_2 = "component"
layer_3 = "material"
layer_4 = "element"

In [5]:
layer_names = (layer_0, layer_1, layer_2, layer_3, layer_4)
all_symbols = {layer_1: "P*", layer_2: "C*", layer_3: "M*", layer_4: "E*"}

metadata = {
    "path": f"data/{folder}/",
    "filename": "metadata.csv",
}
composition = {
    "path": f"data/{folder}/",
    "filename": "composition.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Layer 1": layer_1,
        "Layer 2": layer_2,
        "Layer 3": layer_3,
        "Layer 4": layer_4,
        "Value": "data",
        "Year": "year",
        "Scenario": "scenario",
        "Location": "region",
        "parameterCode": "parameterCode",
        "UoM": "unit",
    },
    "parameterCode": {
        layer_2: "c-p",
        layer_3: "m-c",
        layer_4: "e-m",
    },
}

inputs = {
    "path": f"data/{folder}/",
    "filename": "inputs.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Substance_main_parent": layer_1,
        "Value": "data",
        "Year": "year",
        "Unit": "unit",
    },
}

tcs = {
    "path": f"data/{folder}/",
    "filename": "TCs.csv",
    "mapper": {
        # inflows / outflows
        "input_flow": "inflows",
        "output_flow": "outflows",
        # levels
        "input_layer": "input_layer1_level",
        "input_sub_layer": "input_layer2_level",
        "output_layer": "output_layer1_level",
        # keys
        "input_layer_key": "input_layer1_key",
        "input_sub_layer_key": "input_layer2_key",
        "output_target_key": "output_layer1_key",
        # other columns
        "value": "data",
        "Year": "year",
        "process": "process",
    },
    "all_symbols": {
        layer_1: "P*",
        layer_2: "C*",
        layer_3: "M*",
        layer_4: "E*",
    },
}

---

# Recovery model

In [6]:
model = RecoveryModel(
    name=folder,
    metadata=metadata,
    composition=composition,
    inputs=inputs,
    tcs=tcs,
    layer_names=layer_names,
    save_intermediary_steps=False,
    save_duplicates=False,
)

---

# Metadata

In [7]:
model.dims

(8, 3, 4, 3, 3)

In [8]:
model.solve(aggregate=False, pivot=False)

    flow product component material element    data
0     F1      P1       NaN      NaN     NaN 1000.00
1     F1      P1        C1      NaN     NaN  250.00
2     F1      P1        C1       M1     NaN  130.00
3     F1      P1        C1       M1      E1   91.00
4     F1      P1        C1       M1      E2   39.00
..   ...     ...       ...      ...     ...     ...
175   F8      P1        C3       M2      E2    0.40
176   F8      P2        C1       M1      E1    0.23
177   F8      P2        C1       M2      E2    0.09
178   F8      P2        C2       M1      E1    0.28
179   F8      P2        C2       M2      E2    0.07

[180 rows x 6 columns]

In [9]:
12_000_000 / (2 * 31 * 83 * 8)

291.4885347842985

In [10]:
295 * 8 * 83 * 31 * 2

12144560

In [11]:
model.size

np.int64(864)

In [12]:
model.flows_eqs

         F1  F2  F3  F4  F5  F6  F7  F8
process
T1        1  -1  -1   0   0   1   0   0
T2        0   1   0  -1  -1   0   0   0
T3        0   0   0   0   1   0   1  -1
T4        0   0   1   1   0  -1  -1   0

list(enumerate(model.sub_systems))

In [13]:
print(model)

{   'Layer 1': {'P*': 2, 'P1': 0, 'P2': 1},
    'Layer 2': {'C*': 3, 'C1': 0, 'C2': 1, 'C3': 2},
    'Layer 3': {'M*': 2, 'M1': 0, 'M2': 1},
    'Layer 4': {'E*': 2, 'E1': 0, 'E2': 1},
    'Stock/Flow ID': {   'F1': 0,
                         'F2': 1,
                         'F3': 2,
                         'F4': 3,
                         'F5': 4,
                         'F6': 5,
                         'F7': 6,
                         'F8': 7},
    'Substance_main_parent': {'P*': 2, 'P1': 0, 'P2': 1},
    'Unit': {'Mg': 0},
    'component': {'C*': 3, 'C1': 0, 'C2': 1, 'C3': 2},
    'element': {'E*': 2, 'E1': 0, 'E2': 1},
    'flow': {   'F1': 0,
                'F2': 1,
                'F3': 2,
                'F4': 3,
                'F5': 4,
                'F6': 5,
                'F7': 6,
                'F8': 7},
    'material': {'M*': 2, 'M1': 0, 'M2': 1},
    'parameterCode': {'c-p': 0, 'e-m': 1, 'm-c': 2},
    'process': {'T1': 0, 'T2': 1, 'T3': 3, 'T4': 2},
    'product': {'P*': 2, 'P1': 0, 'P2': 1}}

In [14]:
model.unravel_index(567)

array([[ 5, -1,  2, -1, -1]])

In [15]:
model.dims

(8, 3, 4, 3, 3)

In [16]:
model.size

np.int64(864)

In [17]:
model.flows_eqs

         F1  F2  F3  F4  F5  F6  F7  F8
process
T1        1  -1  -1   0   0   1   0   0
T2        0   1   0  -1  -1   0   0   0
T3        0   0   0   0   1   0   1  -1
T4        0   0   1   1   0  -1  -1   0

In [18]:
list(enumerate(model.sub_systems))

[(0, {'T1', 'T2', 'T4'}), (1, {'T3'})]

In [19]:
print(model)

{   'Layer 1': {'P*': 2, 'P1': 0, 'P2': 1},
    'Layer 2': {'C*': 3, 'C1': 0, 'C2': 1, 'C3': 2},
    'Layer 3': {'M*': 2, 'M1': 0, 'M2': 1},
    'Layer 4': {'E*': 2, 'E1': 0, 'E2': 1},
    'Stock/Flow ID': {   'F1': 0,
                         'F2': 1,
                         'F3': 2,
                         'F4': 3,
                         'F5': 4,
                         'F6': 5,
                         'F7': 6,
                         'F8': 7},
    'Substance_main_parent': {'P*': 2, 'P1': 0, 'P2': 1},
    'Unit': {'Mg': 0},
    'component': {'C*': 3, 'C1': 0, 'C2': 1, 'C3': 2},
    'element': {'E*': 2, 'E1': 0, 'E2': 1},
    'flow': {   'F1': 0,
                'F2': 1,
                'F3': 2,
                'F4': 3,
                'F5': 4,
                'F6': 5,
                'F7': 6,
                'F8': 7},
    'material': {'M*': 2, 'M1': 0, 'M2': 1},
    'parameterCode': {'c-p': 0, 'e-m': 1, 'm-c': 2},
    'process': {'T1': 0, 'T2': 1, 'T3': 3, 'T4': 2},
    'product': {'P*': 2, 'P1': 0, 'P2': 1}}

---

# Linear equations

In [20]:
model.lneqs

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 441 stored elements and shape (864, 864)>

In [21]:
model.lneqs.nanmin()

np.float64(0.0)

---

# Constant terms

In [22]:
model.y

<Compressed Sparse Column sparse array of dtype 'int64'
	with 2 stored elements and shape (864, 1)>

---

# Solver

In [23]:
solution = model.solve(aggregate=True, pivot=True)
solution.fillna("")

flow               F1    F2    F3    F4    F6    F5   F7   F8
layer     key
product   P1  1000.00
product   P2   700.00
component C1   551.00 86.58
component C2   639.00 51.57 39.40 10.31 17.32
component C3   510.00       13.04        1.83
material  M1   920.43 84.53 35.28  7.90 13.72 21.51 4.56
material  M2   779.57 53.62 17.16  2.41  5.42 19.33 4.99
element   E1   676.76 79.40 14.76  3.39  5.66 24.33 2.42 2.32
element   E2  1023.24 58.75 37.68  6.93 13.48 16.51 7.14 1.19

In [24]:
model.solve(aggregate=True, pivot=False)

   flow      layer key    data
0    F1    product  P1 1000.00
1    F1    product  P2  700.00
0    F1  component  C1  551.00
1    F1  component  C2  639.00
2    F1  component  C3  510.00
3    F2  component  C1   86.58
4    F2  component  C2   51.57
5    F3  component  C2   39.40
6    F3  component  C3   13.04
7    F4  component  C2   10.31
8    F6  component  C2   17.32
9    F6  component  C3    1.83
0    F1   material  M1  920.43
1    F1   material  M2  779.57
2    F2   material  M1   84.53
3    F2   material  M2   53.62
4    F3   material  M1   35.28
5    F3   material  M2   17.16
6    F4   material  M1    7.90
7    F4   material  M2    2.41
8    F5   material  M1   21.51
9    F5   material  M2   19.33
10   F6   material  M1   13.72
11   F6   material  M2    5.42
12   F7   material  M1    4.56
13   F7   material  M2    4.99
0    F1    element  E1  676.76
1    F1    element  E2 1023.24
2    F2    element  E1   79.40
3    F2    element  E2   58.75
4    F3    element  E1   14.76
5    F3    element  E2   37.68
6    F4    element  E1    3.39
7    F4    element  E2    6.93
8    F5    element  E1   24.33
9    F5    element  E2   16.51
10   F6    element  E1    5.66
11   F6    element  E2   13.48
12   F7    element  E1    2.42
13   F7    element  E2    7.14
14   F8    element  E1    2.32
15   F8    element  E2    1.19

In [25]:
model.solve(aggregate=False, pivot=True).fillna("")

flow,product,component,material,element,F1,F2,F3,F4,F5,F6,F7,F8
0,P1,,,,1000.00,,,,,,,
1,P1,C1,,,250.00,62.50,,,,,,
2,P1,C1,M1,,130.00,32.50,,,12.68,,,
3,P1,C1,M1,E1,91.00,22.75,,,8.87,,,1.60
4,P1,C1,M1,E2,39.00,9.75,,,3.80,,,
5,P1,C1,M2,,120.00,30.00,,,9.60,,,
6,P1,C1,M2,E1,117.60,29.40,,,9.41,,,
7,P1,C1,M2,E2,2.40,0.60,,,0.19,,,0.01
8,P1,C2,,,590.00,27.76,26.86,5.55,,11.24,,
9,P1,C2,M1,,389.40,18.32,17.73,3.66,1.83,7.42,2.08,
10,P1,C2,M1,E1,109.03,5.13,4.96,1.03,0.51,2.08,0.58,0.17
11,P1,C2,M1,E2,280.37,13.19,12.76,2.64,1.32,5.34,1.50,
12,P1,C2,M2,,200.60,9.44,9.13,1.89,4.72,3.82,2.04,
13,P1,C2,M2,E1,16.05,0.76,0.73,0.15,0.38,0.31,0.16,
14,P1,C2,M2,E2,184.55,8.68,8.40,1.74,4.34,3.52,1.88,0.62
15,P1,C3,,,160.00,,13.04,,,1.83,,
16,P1,C3,M1,,78.40,,6.39,,,0.89,0.83,
17,P1,C3,M1,E1,25.09,,2.04,,,0.29,0.27,0.04
18,P1,C3,M1,E2,53.31,,4.34,,,0.61,0.56,
19,P1,C3,M2,,81.60,,6.65,,,0.93,2.59,
20,P1,C3,M2,E1,14.69,,1.20,,,0.17,0.47,
21,P1,C3,M2,E2,66.91,,5.45,,,0.76,2.13,0.40
22,P2,,,,700.00,,,,,,,
23,P2,C1,,,301.00,24.08,,,,,,
24,P2,C1,M1,,156.52,12.52,,,4.88,,,
25,P2,C1,M1,E1,40.70,3.26,,,1.27,,,0.23
26,P2,C1,M1,E2,115.82,9.27,,,3.61,,,
27,P2,C1,M2,,144.48,11.56,,,3.70,,,
28,P2,C1,M2,E1,88.13,7.05,,,2.26,,,
29,P2,C1,M2,E2,56.35,4.51,,,1.44,,,0.09
30,P2,C2,,,49.00,23.81,12.54,4.76,,6.07,,
31,P2,C2,M1,,43.61,21.19,11.16,4.24,2.12,5.41,1.66,
32,P2,C2,M1,E1,20.06,9.75,5.13,1.95,0.97,2.49,0.76,0.28
33,P2,C2,M1,E2,23.55,11.44,6.03,2.29,1.14,2.92,0.89,
34,P2,C2,M2,,5.39,2.62,1.38,0.52,1.31,0.67,0.36,
35,P2,C2,M2,E1,2.70,1.31,0.69,0.26,0.65,0.33,0.18,
36,P2,C2,M2,E2,2.70,1.31,0.69,0.26,0.65,0.33,0.18,0.07
37,P2,C3,,,350.00,,,,,,,
38,P2,C3,M1,,122.50,,,,,,,
39,P2,C3,M1,E1,85.75,,,,,,,
40,P2,C3,M1,E2,36.75,,,,,,,
41,P2,C3,M2,,227.50,,,,,,,
42,P2,C3,M2,E1,65.97,,,,,,,
43,P2,C3,M2,E2,161.53,,,,,,,

In [26]:
model.solve(aggregate=False, pivot=False).fillna("")

    flow product component material element    data
0     F1      P1                            1000.00
1     F1      P1        C1                   250.00
2     F1      P1        C1       M1          130.00
3     F1      P1        C1       M1      E1   91.00
4     F1      P1        C1       M1      E2   39.00
..   ...     ...       ...      ...     ...     ...
175   F8      P1        C3       M2      E2    0.40
176   F8      P2        C1       M1      E1    0.23
177   F8      P2        C1       M2      E2    0.09
178   F8      P2        C2       M1      E1    0.28
179   F8      P2        C2       M2      E2    0.07

[180 rows x 6 columns]

## Output restructuring

In [27]:
sol = model.solve(aggregate=False, pivot=False)

base_cols = ["flow"]  # add countries, years, etc. (if needed)
levels = ["product", "component", "material", "element"]  # to be adapted to the model
results = dict()

for i, level in enumerate(levels):

    # consider the rows where the level is not empty but the sublevels are empty
    filter_mask = (sol[level].notna()) & (sol[levels[i + 1 :]].isna().all(axis=1))

    # define the columns to drop
    cols_to_drop = [col for col in levels if col != level]
    cols_to_keep = base_cols + [level]

    # sum the data for the flows and the level (disregarding the sublevels)
    temp_df = sol.loc[filter_mask].groupby(cols_to_keep).sum()

    # save the results (drop the columns that are not of interest)
    results[level] = temp_df.drop(columns=cols_to_drop)

    # # Uncomment to display the results
    # display(results[level])

# Check the results (e.g. for elements)
results["element"]

                data
flow element
F1   E1       676.76
F1   E2      1023.24
F2   E1        79.40
F2   E2        58.75
F3   E1        14.76
F3   E2        37.68
F4   E1         3.39
F4   E2         6.93
F5   E1        24.33
F5   E2        16.51
F6   E1         5.66
F6   E2        13.48
F7   E1         2.42
F7   E2         7.14
F8   E1         2.32
F8   E2         1.19

In [ ]:
# ---------------------- TEST
cols = ["product", "component", "material", "element", "WEEE_generatedDedicated"]
TEST_REST = model.solve(aggregate=False, pivot=True).fillna("")[cols]
TEST_REST

In [ ]:
model.dims

In [ ]:
counter = TEST_REST[cols[:-1]].apply(np.unique)

print(np.prod(counter.apply(len)))
print(counter.apply(len))

In [ ]:
temp = TEST_REST[TEST_REST["product"] == "WEEE_Cat3"]

counter = temp[cols[:-1]].apply(np.unique)

print(np.prod(counter.apply(len)))
print(counter.apply(len))

---

# Performance

In [ ]:
%%prun -l 20 -s cumulative

model = RecoveryModel(
    name=folder,
    metadata=metadata,
    composition=composition,
    inputs=inputs,
    tcs=tcs,
    layer_names=layer_names,
    save_intermediary_steps=False,
    save_duplicates=False,
)

In [ ]:
cProfile.run(
    "RecoveryModel(name=folder, metadata=metadata, composition=composition, inputs=inputs, tcs=tcs, layer_names=layer_names, save_intermediary_steps=False, save_duplicates=False)",
    "performance/RecoveryModel.pstats",
)

cProfile.run(
    "model.solve(aggregate=False, pivot=True)",
    "performance/Solver.pstats",
)

# # ! then go into results/performances/ and run the following commands
# # (-n 2 means cutoff at 2%)
# gprof2dot -f pstats -n 1 RecoveryModel.pstats | dot -Tpng -o RecoveryModel.png
# gprof2dot -f pstats -n 1 Solver.pstats | dot -Tpng -o Solver.png

In [5]:
cProfile.run(
    "RecoveryModel(name=folder, metadata=metadata, composition=composition, inputs=inputs, tcs=tcs, layer_names=layer_names, save_intermediary_steps=False, save_duplicates=False)",
    "performance/RecoveryModel.prof",
)

cProfile.run(
    "model.solve(aggregate=False, pivot=True)",
    "performance/Solver.prof",
)

# # ! then go into results/performances/ and run the following commands
# snakeviz RecoveryModel.prof
# snakeviz Solver.prof  # 22.6s

          product            component                   material element  \
8022    WEEE_Cat1                  NaN                        NaN     NaN
8023    WEEE_Cat1  ComponentShadowWEEE                        NaN     NaN
8024    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys     NaN
8025    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      Ag
8026    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      As
...           ...                  ...                        ...     ...
29563  WEEE_Cat4b   passiveJunctionBox              CuAndCuAlloys      Zr
29564  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials     NaN
29565  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials      Ag
29566  WEEE_Cat4b   passiveJunctionBox                   plastics     NaN
29567  WEEE_Cat4b   passiveJunctionBox                   plastics      Ag

              process  WEEE_generatedComplementaryExported  \
8022   WEEE_generated                           -135511.97
8023   WEEE_generated                             -1162.72
8024   WEEE_generated                               -79.03
8025   WEEE_generated                               -11.68
8026   WEEE_generated                                -0.21
...               ...                                  ...
29563     dismantling                                 0.00
29564     dismantling                                 0.00
29565     dismantling                                 0.00
29566     dismantling                                 0.00
29567     dismantling                                 0.00

       WEEE_2RM_thermal2Smelter_other  WEEE_mechRec2_chem  \
8022                              NaN                 NaN
8023                              NaN                 NaN
8024                              NaN                 NaN
8025                              NaN                 NaN
8026                              NaN                 NaN
...                               ...                 ...
29563                             NaN                 NaN
29564                             NaN                 NaN
29565                             NaN                 NaN
29566                             NaN                 NaN
29567                             NaN                 NaN

       WEEE_generatedComplementaryUndocumented  \
8022                                -830010.82
8023                                  -7121.63
8024                                   -484.07
8025                                    -71.53
8026                                     -1.28
...                                        ...
29563                                     0.00
29564                                     0.00
29565                                     0.00
29566                                     0.00
29567                                     0.00

       WEEE_2RM_mechRec1Smelter_other  ...  WEEE_2RM_chem2Smelter_other  \
8022                              NaN  ...                          NaN
8023                             0.00  ...                          NaN
8024                             0.00  ...                          NaN
8025                             0.00  ...                          NaN
8026                             0.00  ...                          NaN
...                               ...  ...                          ...
29563                           -2.62  ...                          NaN
29564                           -1.04  ...                          NaN
29565                           -1.04  ...                          NaN
29566                           -3.71  ...                          NaN
29567                           -3.71  ...                          NaN

       WEEE_generatedComplementaryMetalScrap  WEEE_collected  \
8022                              -355718.92      -948583.79
8023                                -3052.13        -8139.01
8024                                 -207.46         -553.23
8025                                  -30.66          -81.75
8026                                   -0.55           -1.46
...                                      ...             ...
29563                                   0.00            0.00
29564                                   0.00            0.00
29565                                   0.00            0.00
29566                                   0.00            0.00
29567                                   0.00            0.00

       WEEE_generatedDedicated  WEEE_mechRec2_thermal  WEEE_mechRec1_mechRec2  \
8022                1693899.63                    NaN                     NaN
8023                  14533.95                    NaN                    0.00
8024                    987.90                    NaN                    0.00
8025                    145.98                    NaN                    0.00
8026                      2.60                    NaN                    0.00
...                        ...                    ...                     ...
29563                     0.00                    NaN                   -2.99
29564                     0.00                    NaN                   -1.18
29565                     0.00                    NaN                   -1.18
29566                     0.00                    NaN                   -4.23
29567                     0.00                    NaN                   -4.23

       WEEE_chem_thermal  WEEE_categ_mechRec2  WEEE_categ_mechRec1  \
8022                 NaN                 0.00                 0.00
8023                 NaN                 0.00                 0.00
8024                 NaN                 0.00                 0.00
8025                 NaN                 0.00                 0.00
8026                 NaN                 0.00                 0.00
...                  ...                  ...                  ...
29563                NaN                 0.00                 5.24
29564                NaN                 0.00                 2.07
29565                NaN                 0.00                 2.07
29566                NaN                 0.00                 7.42
29567                NaN                 0.00                 7.42

       mass_balance
8022    -1507570.67
8023      -12935.21
8024        -879.23
8025        -129.92
8026          -2.32
...             ...
29563         -0.37
29564         -0.14
29565         -0.14
29566         -0.52
29567         -0.52

[8107 rows x 25 columns]