In [30]:
import cProfile
import pandas as pd
from src.recovery_model import RecoveryModel

pd.set_option("multi_sparse", False)
pd.set_option("display.float_format", "{:.2f}".format)

In [31]:
# Select a folder for the data to be used
folder = "test_2"  # test_1  test_2  Toy_WEEE_v2
layer_0 = "flow"
layer_1 = "product"
layer_2 = "component"
layer_3 = "material"
layer_4 = "element"

In [32]:
layer_names = (layer_0, layer_1, layer_2, layer_3, layer_4)
all_symbols = {layer_1: "P*", layer_2: "C*", layer_3: "M*", layer_4: "E*"}

metadata = {
    "path": f"data/{folder}/",
    "filename": "metadata.csv",
}
composition = {
    "path": f"data/{folder}/",
    "filename": "composition.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Layer 1": layer_1,
        "Layer 2": layer_2,
        "Layer 3": layer_3,
        "Layer 4": layer_4,
        "Value": "data",
        "Year": "year",
        "Scenario": "scenario",
        "Location": "region",
        "parameterCode": "parameterCode",
        "UoM": "unit",
    },
    "parameterCode": {
        layer_2: "c-p",
        layer_3: "m-c",
        layer_4: "e-m",
    },
}

inputs = {
    "path": f"data/{folder}/",
    "filename": "inputs.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Substance_main_parent": layer_1,
        "Value": "data",
        "Year": "year",
        "Unit": "unit",
    },
}

tcs = {
    "path": f"data/{folder}/",
    "filename": "TCs.csv",
    "mapper": {
        # inflows / outflows
        "input_flow": "inflows",
        "output_flow": "outflows",
        # levels
        "input_layer": "input_layer1_level",
        "input_sub_layer": "input_layer2_level",
        "output_layer": "output_layer1_level",
        # keys
        "input_layer_key": "input_layer1_key",
        "input_sub_layer_key": "input_layer2_key",
        "output_target_key": "output_layer1_key",
        # other columns
        "value": "data",
        "Year": "year",
        "process": "process",
    },
    "all_symbols": {
        layer_1: "P*",
        layer_2: "C*",
        layer_3: "M*",
        layer_4: "E*",
    },
}

---

# Recovery model

In [33]:
model = RecoveryModel(
    name=folder,
    metadata=metadata,
    composition=composition,
    inputs=inputs,
    tcs=tcs,
    layer_names=layer_names,
    save_intermediary_steps=False,
    save_duplicates=False,
)

---

# Metadata

In [34]:
model.dims

In [35]:
model.size

(19, 8, 83, 31, 18)

In [36]:
model.flows_eqs

391096

list(enumerate(model.sub_systems))

In [37]:
print(model)

array([46891])

In [38]:
model.unravel_index(567)

array([[ 0, -1,  0, -1,  8]])

In [39]:
model.dims

(19, 8, 83, 31, 18)

In [40]:
model.size

7039728

In [41]:
model.flows_eqs

,WEEE_2RM_chem2Smelter_other,WEEE_2RM_mechRec1Smelter_other,WEEE_2RM_mechRec2Smelter_other,WEEE_2RM_thermal2Smelter_other,WEEE_categ_mechRec1,WEEE_categ_mechRec2,WEEE_chem_thermal,WEEE_collected,WEEE_generatedComplementaryExported,WEEE_generatedComplementaryMSW,WEEE_generatedComplementaryMetalScrap,WEEE_generatedComplementaryUndocumented,WEEE_generatedDedicated,WEEE_mechRec1_mechRec2,WEEE_mechRec2_chem,WEEE_mechRec2_thermal,WEEE_thermal_chem,WEEE_wasteBinIncineration,WEEE_wasteBinLandfill
process,,,,,,,,,,,,,,,,,,,
WEEE_complementary_collection(MSW),0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,-1,-1
WEEE_generated,0,0,0,0,0,0,0,-1,-1,-1,-1,-1,1,0,0,0,0,0,0
categorizing,0,0,0,0,-1,-1,0,1,0,0,0,0,0,0,0,0,0,0,0
chemical process,-1,0,0,0,0,0,-1,0,0,0,0,0,0,0,1,0,1,0,0
dismantling,0,-1,0,0,1,0,0,0,0,0,0,0,0,-1,0,0,0,0,0
shredding,0,0,-1,0,0,1,0,0,0,0,0,0,0,1,-1,-1,0,0,0
thermal process,0,0,0,-1,0,0,1,0,0,0,0,0,0,0,0,1,-1,0,0

In [42]:
list(enumerate(model.sub_systems))

[(0, {'WEEE_generated'}),
 (1, {'WEEE_complementary_collection(MSW)'}),
 (2, {'categorizing'}),
 (3, {'dismantling'}),
 (4, {'shredding'}),
 (5, {'chemical process', 'thermal process'})]

In [43]:
print(model)

{   'Layer 1': {   'P*': 7,
                   'WEEE_Cat1': 0,
                   'WEEE_Cat2': 1,
                   'WEEE_Cat3': 2,
                   'WEEE_Cat4a': 3,
                   'WEEE_Cat4b': 4,
                   'WEEE_Cat5': 5,
                   'WEEE_Cat6': 6},
    'Layer 2': {   'C*': 82,
                   'ComponentShadowWEEE': 0,
                   'ConductivitySensor': 1,
                   'LED': 2,
                   'LidarSensor (&lt;15cm)': 3,
                   'MagnetSensor': 4,
                   'PCBWEEECat': 5,
                   'PCBunspecified': 6,
                   'PVBacksheet': 7,
                   'PVEncapsulationEVA': 8,
                   'PVFrameAl': 9,
                   'PVSolarGlass': 10,
                   'PVcellSi': 11,
                   'WEEEEvaporator': 12,
                   'brush': 13,
                   'cableUnspecified': 14,
                   'cableWOPlug': 15,
                   'cableWPlug': 16,
                   'cableWithConnector': 17,
                   'cables': 18,
                   'cablewire': 19,
                   'capElectrolytic': 20,
                   'casingPlasticBased': 21,
                   'casingSteelBased': 22,
                   'casingUnspecified': 23,
                   'coldCathodeLamp': 24,
                   'compContainHazardSubst': 25,
                   'compressor': 26,
                   'condensator': 27,
                   'contactor': 28,
                   'displayCRT': 29,
                   'displayLCD': 30,
                   'displayLCDunder100cm2': 31,
                   'displayOther': 32,
                   'displayPlasma': 33,
                   'driveCDDExt': 34,
                   'driveCDDInt': 35,
                   'driveFDD': 36,
                   'driveHDD': 37,
                   'driveUnspecified': 38,
                   'electricEngine': 39,
                   'filterFoamBased': 40,
                   'fuse': 41,
                   'gear': 42,
                   'heatingCoolingEEEairCondenser': 43,
                   'heatingCoolingEEEfan': 44,
                   'heatingCoolingEEEheatSink': 45,
                   'inductor': 46,
                   'insulation': 47,
                   'keyboard': 48,
                   'knob': 49,
                   'lenseAssembly': 50,
                   'lighting': 51,
                   'lightingFlash': 52,
                   'magnetPermanent': 53,
                   'magnetron': 54,
                   'mainboardInclCPUgpu': 55,
                   'non-electricCoil': 56,
                   'nonElectricCoil': 57,
                   'onOffSwitch': 58,
                   'otherElectricCompUnspecified': 59,
                   'otherNonElectricCompUnspecified': 60,
                   'passiveJunctionBox': 61,
                   'pcbWEEECat': 62,
                   'plug': 63,
                   'powerSupply': 64,
                   'printedCircuitBoard': 65,
                   'pump': 66,
                   'refrigerant': 67,
                   'remoteControl': 68,
                   'resistor': 69,
                   'rotor': 70,
                   'screw': 71,
                   'sensorUnspecified': 72,
                   'shadowComponentWEEE': 73,
                   'solenoidValve': 74,
                   'speakerEEE2': 75,
                   'switch': 76,
                   'tonerCartridge': 77,
                   'transformator': 78,
                   'transmission': 79,
                   'transmitter': 80,
                   'wheel': 81},
    'Layer 3': {   'AlAndAlAlloys': 0,
                   'CuAndCuAlloys': 1,
                   'M*': 30,
                   'MaterialShadowWEEE': 2,
                   'aggregateBinderMixedMaterials': 3,
                   'bitumen': 4,
                   'carbon': 5,
                   'ceramicComposites': 6,
                   'concrete': 7,
                   'ferrousMetals': 8,
                   'glass': 9,
                   'glassAndCeramics': 10,
                   'ironWroughtAndCast': 11,
                   'non-ferrousMetals': 12,
                   'oil4': 13,
                   'otherFerrousAlloys': 14,
                   'otherMetalsAndMetalAlloys': 15,
                   'otherMinerals': 16,
                   'otherOrUndefinedMaterials': 17,
                   'otherOrganics': 18,
                   'plasticComposites': 19,
                   'plastics': 20,
                   'polymerPA6GF30': 21,
                   'polymerPPGF30': 22,
                   'polymerPPTF20': 23,
                   'polymerPPTF30': 24,
                   'reinforcedPlastics': 25,
                   'sand': 26,
                   'steelAndSteelAlloys': 27,
                   'undefinedAndMixedMaterials': 28,
                   'wood': 29},
    'Layer 4': {   'Ag': 0,
                   'Al': 1,
                   'As': 2,
                   'Bi': 3,
                   'Ca': 4,
                   'Cl': 5,
                   'Cu': 6,
                   'Dy': 7,
                   'E*': 17,
                   'Ga': 8,
                   'Mn': 9,
                   'Mo': 10,
                   'O': 11,
                   'Pd': 12,
                   'Sc': 13,
                   'Sm': 14,
                   'Sr': 15,
                   'Zr': 16},
    'Location': {'EU27+4': 0},
    'Reference': {'M18': 0},
    'Scenario': {'OBS': 0},
    'Stock/Flow ID': {   'WEEE_2RM_chem2Smelter_other': 10,
                         'WEEE_2RM_mechRec1Smelter_other': 4,
                         'WEEE_2RM_mechRec2Smelter_other': 7,
                         'WEEE_2RM_thermal2Smelter_other': 1,
                         'WEEE_categ_mechRec1': 18,
                         'WEEE_categ_mechRec2': 17,
                         'WEEE_chem_thermal': 16,
                         'WEEE_collected': 12,
                         'WEEE_generatedComplementaryExported': 0,
                         'WEEE_generatedComplementaryMSW': 5,
                         'WEEE_generatedComplementaryMetalScrap': 11,
                         'WEEE_generatedComplementaryUndocumented': 3,
                         'WEEE_generatedDedicated': 13,
                         'WEEE_mechRec1_mechRec2': 15,
                         'WEEE_mechRec2_chem': 2,
                         'WEEE_mechRec2_thermal': 14,
                         'WEEE_thermal_chem': 9,
                         'WEEE_wasteBinIncineration': 8,
                         'WEEE_wasteBinLandfill': 6},
    'Substance_main_parent': {   'P*': 7,
                                 'WEEE_Cat1': 0,
                                 'WEEE_Cat2': 1,
                                 'WEEE_Cat3': 2,
                                 'WEEE_Cat4a': 3,
                                 'WEEE_Cat4b': 4,
                                 'WEEE_Cat5': 5,
                                 'WEEE_Cat6': 6},
    'Unit': {'wt%': 0},
    'UoM': {'wt%': 0},
    'Waste Stream': {'WEEE': 0},
    'component': {   'C*': 82,
                     'ComponentShadowWEEE': 0,
                     'ConductivitySensor': 1,
                     'LED': 2,
                     'LidarSensor (&lt;15cm)': 3,
                     'MagnetSensor': 4,
                     'PCBWEEECat': 5,
                     'PCBunspecified': 6,
                     'PVBacksheet': 7,
                     'PVEncapsulationEVA': 8,
                     'PVFrameAl': 9,
                     'PVSolarGlass': 10,
                     'PVcellSi': 11,
                     'WEEEEvaporator': 12,
                     'brush': 13,
                     'cableUnspecified': 14,
                     'cableWOPlug': 15,
                     'cableWPlug': 16,
                     'cableWithConnector': 17,
                     'cables': 18,
                     'cablewire': 19,
                     'capElectrolytic': 20,
                     'casingPlasticBased': 21,
                     'casingSteelBased': 22,
                     'casingUnspecified': 23,
                     'coldCathodeLamp': 24,
                     'compContainHazardSubst': 25,
                     'compressor': 26,
                     'condensator': 27,
                     'contactor': 28,
                     'displayCRT': 29,
                     'displayLCD': 30,
                     'displayLCDunder100cm2': 31,
                     'displayOther': 32,
                     'displayPlasma': 33,
                     'driveCDDExt': 34,
                     'driveCDDInt': 35,
                     'driveFDD': 36,
                     'driveHDD': 37,
                     'driveUnspecified': 38,
                     'electricEngine': 39,
                     'filterFoamBased': 40,
                     'fuse': 41,
                     'gear': 42,
                     'heatingCoolingEEEairCondenser': 43,
                     'heatingCoolingEEEfan': 44,
                     'heatingCoolingEEEheatSink': 45,
                     'inductor': 46,
                     'insulation': 47,
                     'keyboard': 48,
                     'knob': 49,
                     'lenseAssembly': 50,
                     'lighting': 51,
                     'lightingFlash': 52,
                     'magnetPermanent': 53,
                     'magnetron': 54,
                     'mainboardInclCPUgpu': 55,
                     'non-electricCoil': 56,
                     'nonElectricCoil': 57,
                     'onOffSwitch': 58,
                     'otherElectricCompUnspecified': 59,
                     'otherNonElectricCompUnspecified': 60,
                     'passiveJunctionBox': 61,
                     'pcbWEEECat': 62,
                     'plug': 63,
                     'powerSupply': 64,
                     'printedCircuitBoard': 65,
                     'pump': 66,
                     'refrigerant': 67,
                     'remoteControl': 68,
                     'resistor': 69,
                     'rotor': 70,
                     'screw': 71,
                     'sensorUnspecified': 72,
                     'shadowComponentWEEE': 73,
                     'solenoidValve': 74,
                     'speakerEEE2': 75,
                     'switch': 76,
                     'tonerCartridge': 77,
                     'transformator': 78,
                     'transmission': 79,
                     'transmitter': 80,
                     'wheel': 81},
    'element': {   'Ag': 0,
                   'Al': 1,
                   'As': 2,
                   'Bi': 3,
                   'Ca': 4,
                   'Cl': 5,
                   'Cu': 6,
                   'Dy': 7,
                   'E*': 17,
                   'Ga': 8,
                   'Mn': 9,
                   'Mo': 10,
                   'O': 11,
                   'Pd': 12,
                   'Sc': 13,
                   'Sm': 14,
                   'Sr': 15,
                   'Zr': 16},
    'flow': {   'WEEE_2RM_chem2Smelter_other': 10,
                'WEEE_2RM_mechRec1Smelter_other': 4,
                'WEEE_2RM_mechRec2Smelter_other': 7,
                'WEEE_2RM_thermal2Smelter_other': 1,
                'WEEE_categ_mechRec1': 18,
                'WEEE_categ_mechRec2': 17,
                'WEEE_chem_thermal': 16,
                'WEEE_collected': 12,
                'WEEE_generatedComplementaryExported': 0,
                'WEEE_generatedComplementaryMSW': 5,
                'WEEE_generatedComplementaryMetalScrap': 11,
                'WEEE_generatedComplementaryUndocumented': 3,
                'WEEE_generatedDedicated': 13,
                'WEEE_mechRec1_mechRec2': 15,
                'WEEE_mechRec2_chem': 2,
                'WEEE_mechRec2_thermal': 14,
                'WEEE_thermal_chem': 9,
                'WEEE_wasteBinIncineration': 8,
                'WEEE_wasteBinLandfill': 6},
    'material': {   'AlAndAlAlloys': 0,
                    'CuAndCuAlloys': 1,
                    'M*': 30,
                    'MaterialShadowWEEE': 2,
                    'aggregateBinderMixedMaterials': 3,
                    'bitumen': 4,
                    'carbon': 5,
                    'ceramicComposites': 6,
                    'concrete': 7,
                    'ferrousMetals': 8,
                    'glass': 9,
                    'glassAndCeramics': 10,
                    'ironWroughtAndCast': 11,
                    'non-ferrousMetals': 12,
                    'oil4': 13,
                    'otherFerrousAlloys': 14,
                    'otherMetalsAndMetalAlloys': 15,
                    'otherMinerals': 16,
                    'otherOrUndefinedMaterials': 17,
                    'otherOrganics': 18,
                    'plasticComposites': 19,
                    'plastics': 20,
                    'polymerPA6GF30': 21,
                    'polymerPPGF30': 22,
                    'polymerPPTF20': 23,
                    'polymerPPTF30': 24,
                    'reinforcedPlastics': 25,
                    'sand': 26,
                    'steelAndSteelAlloys': 27,
                    'undefinedAndMixedMaterials': 28,
                    'wood': 29},
    'parameterCode': {'c-p': 0, 'e-m': 1, 'm-c': 2},
    'process': {   'WEEE_complementary_collection(MSW)': 0,
                   'WEEE_generated': 1,
                   'categorizing': 2,
                   'chemical process': 3,
                   'dismantling': 4,
                   'shredding': 5,
                   'thermal process': 6},
    'product': {   'P*': 7,
                   'WEEE_Cat1': 0,
                   'WEEE_Cat2': 1,
                   'WEEE_Cat3': 2,
                   'WEEE_Cat4a': 3,
                   'WEEE_Cat4b': 4,
                   'WEEE_Cat5': 5,
                   'WEEE_Cat6': 6},
    'region': {'EU27+4': 0},
    'scenario': {'OBS': 0},
    'technology': {},
    'unit': {'wt%': 0}}

---

# Linear equations

In [44]:
model.lneqs

<7039728x7039728 sparse matrix of type '<class 'numpy.float64'>'
	with 3309312 stored elements in Compressed Sparse Row format>

In [45]:
model.lneqs.nanmin()

0.0

---

# Constant terms

In [46]:
model.y

<7039728x1 sparse array of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Column format>

---

# Solver

In [47]:
solution = model.solve(aggregate=True, pivot=True)
solution.fillna("")

          product            component                   material element  \
8022    WEEE_Cat1                  NaN                        NaN     NaN
8023    WEEE_Cat1  ComponentShadowWEEE                        NaN     NaN
8024    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys     NaN
8025    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      Ag
8026    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      As
...           ...                  ...                        ...     ...
29563  WEEE_Cat4b   passiveJunctionBox              CuAndCuAlloys      Zr
29564  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials     NaN
29565  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials      Ag
29566  WEEE_Cat4b   passiveJunctionBox                   plastics     NaN
29567  WEEE_Cat4b   passiveJunctionBox                   plastics      Ag

              process  WEEE_generatedComplementaryExported  \
8022   WEEE_generated                          -135,511.97
8023   WEEE_generated                            -1,162.72
8024   WEEE_generated                               -79.03
8025   WEEE_generated                               -11.68
8026   WEEE_generated                                -0.21
...               ...                                  ...
29563     dismantling                                 0.00
29564     dismantling                                 0.00
29565     dismantling                                 0.00
29566     dismantling                                 0.00
29567     dismantling                                 0.00

       WEEE_2RM_thermal2Smelter_other  WEEE_mechRec2_chem  \
8022                              NaN                 NaN
8023                              NaN                 NaN
8024                              NaN                 NaN
8025                              NaN                 NaN
8026                              NaN                 NaN
...                               ...                 ...
29563                             NaN                 NaN
29564                             NaN                 NaN
29565                             NaN                 NaN
29566                             NaN                 NaN
29567                             NaN                 NaN

       WEEE_generatedComplementaryUndocumented  \
8022                               -830,010.82
8023                                 -7,121.63
8024                                   -484.07
8025                                    -71.53
8026                                     -1.28
...                                        ...
29563                                     0.00
29564                                     0.00
29565                                     0.00
29566                                     0.00
29567                                     0.00

       WEEE_2RM_mechRec1Smelter_other  ...  WEEE_2RM_chem2Smelter_other  \
8022                              NaN  ...                          NaN
8023                             0.00  ...                          NaN
8024                             0.00  ...                          NaN
8025                             0.00  ...                          NaN
8026                             0.00  ...                          NaN
...                               ...  ...                          ...
29563                           -2.62  ...                          NaN
29564                           -1.04  ...                          NaN
29565                           -1.04  ...                          NaN
29566                           -3.71  ...                          NaN
29567                           -3.71  ...                          NaN

       WEEE_generatedComplementaryMetalScrap  WEEE_collected  \
8022                             -355,718.92     -948,583.79
8023                               -3,052.13       -8,139.01
8024                                 -207.46         -553.23
8025                                  -30.66          -81.75
8026                                   -0.55           -1.46
...                                      ...             ...
29563                                   0.00            0.00
29564                                   0.00            0.00
29565                                   0.00            0.00
29566                                   0.00            0.00
29567                                   0.00            0.00

       WEEE_generatedDedicated  WEEE_mechRec2_thermal  WEEE_mechRec1_mechRec2  \
8022              1,693,899.63                    NaN                     NaN
8023                 14,533.95                    NaN                    0.00
8024                    987.90                    NaN                    0.00
8025                    145.98                    NaN                    0.00
8026                      2.60                    NaN                    0.00
...                        ...                    ...                     ...
29563                     0.00                    NaN                   -2.99
29564                     0.00                    NaN                   -1.18
29565                     0.00                    NaN                   -1.18
29566                     0.00                    NaN                   -4.23
29567                     0.00                    NaN                   -4.23

       WEEE_chem_thermal  WEEE_categ_mechRec2  WEEE_categ_mechRec1  \
8022                 NaN                 0.00                 0.00
8023                 NaN                 0.00                 0.00
8024                 NaN                 0.00                 0.00
8025                 NaN                 0.00                 0.00
8026                 NaN                 0.00                 0.00
...                  ...                  ...                  ...
29563                NaN                 0.00                 5.24
29564                NaN                 0.00                 2.07
29565                NaN                 0.00                 2.07
29566                NaN                 0.00                 7.42
29567                NaN                 0.00                 7.42

       mass_balance
8022  -1,507,570.67
8023     -12,935.21
8024        -879.23
8025        -129.92
8026          -2.32
...             ...
29563         -0.37
29564         -0.14
29565         -0.14
29566         -0.52
29567         -0.52

[8107 rows x 25 columns]

,flow,WEEE_categ_mechRec1,WEEE_categ_mechRec2,WEEE_collected,WEEE_generatedComplementaryExported,WEEE_generatedComplementaryMSW,WEEE_generatedComplementaryMetalScrap,WEEE_generatedComplementaryUndocumented,WEEE_generatedDedicated,WEEE_wasteBinIncineration,WEEE_wasteBinLandfill,WEEE_2RM_mechRec1Smelter_other,WEEE_mechRec1_mechRec2,WEEE_2RM_mechRec2Smelter_other,WEEE_mechRec2_chem,WEEE_mechRec2_thermal,WEEE_2RM_chem2Smelter_other,WEEE_2RM_thermal2Smelter_other,WEEE_chem_thermal,WEEE_thermal_chem
layer,key,,,,,,,,,,,,,,,,,,,
product,WEEE_Cat1,"322,518.49","464,806.06","948,583.79","135,511.97","931,644.80","355,718.92","830,010.82","1,693,899.63","139,746.72","335,392.13",,,,,,,,,
product,WEEE_Cat2,"99,905.12","16,650.85","185,009.48","123,339.65","534,471.82","328,905.73","472,801.99","1,027,830.42","112,239.08","90,860.21",,,,,,,,,
product,WEEE_Cat3,"7,493.33","5,057.99","18,733.31","20,937.23","62,811.70","16,529.39","25,345.07","110,195.96","21,355.98","18,215.39",,,,,,,,,
product,WEEE_Cat4a,"175,777.78","527,333.33","1,255,555.55","418,518.52","1,720,576.12","2,092,592.58","1,720,576.12","4,650,205.74","980,728.39","498,967.08",,,,,,,,,
product,WEEE_Cat4b,"4,347.91","29,891.87","54,348.86","48,473.30","42,597.75","80,788.84","36,722.20","146,888.80","23,002.79","8,945.53",,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
element,Pd,"4,137.83","7,690.37","18,586.28","21,298.14","32,164.03","36,470.36","28,354.23","81,649.37","11,948.30","9,371.56",303.03,213.77,148.96,,,,,,
element,Sc,"7,528.58","14,946.98","36,822.64","50,838.89","70,756.67","80,675.45","57,926.83","175,588.23","27,577.00","21,088.69",637.06,427.59,145.71,,,,,,
element,Sm,"30,229.69","57,479.05","131,101.18","122,340.48","204,186.00","214,361.00","176,274.54","499,460.71","74,740.18","63,308.09",983.57,983.42,"3,675.50",4.56,3.01,,,,
element,Sr,"1,269.21","3,409.12","8,057.79","3,025.84","11,146.11","12,886.48","10,843.80","29,455.21","5,964.28","3,257.56",7.27,7.27,13.49,,,,,,
element,Zr,"25,075.16","49,866.66","113,587.20","96,068.05","169,006.84","186,727.96","155,009.81","432,165.10","64,735.23","51,515.88","1,378.48","1,231.60","3,025.12",0.08,0.30,,,,

In [48]:
model.solve(aggregate=True, pivot=False)

          product            component                   material element  \
8022    WEEE_Cat1                  NaN                        NaN     NaN
8023    WEEE_Cat1  ComponentShadowWEEE                        NaN     NaN
8024    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys     NaN
8025    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      Ag
8026    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      As
...           ...                  ...                        ...     ...
29563  WEEE_Cat4b   passiveJunctionBox              CuAndCuAlloys      Zr
29564  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials     NaN
29565  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials      Ag
29566  WEEE_Cat4b   passiveJunctionBox                   plastics     NaN
29567  WEEE_Cat4b   passiveJunctionBox                   plastics      Ag

              process  WEEE_generatedComplementaryExported  \
8022   WEEE_generated                          -135,511.97
8023   WEEE_generated                            -1,162.72
8024   WEEE_generated                               -79.03
8025   WEEE_generated                               -11.68
8026   WEEE_generated                                -0.21
...               ...                                  ...
29563     dismantling                                 0.00
29564     dismantling                                 0.00
29565     dismantling                                 0.00
29566     dismantling                                 0.00
29567     dismantling                                 0.00

       WEEE_2RM_thermal2Smelter_other  WEEE_mechRec2_chem  \
8022                              NaN                 NaN
8023                              NaN                 NaN
8024                              NaN                 NaN
8025                              NaN                 NaN
8026                              NaN                 NaN
...                               ...                 ...
29563                             NaN                 NaN
29564                             NaN                 NaN
29565                             NaN                 NaN
29566                             NaN                 NaN
29567                             NaN                 NaN

       WEEE_generatedComplementaryUndocumented  \
8022                               -830,010.82
8023                                 -7,121.63
8024                                   -484.07
8025                                    -71.53
8026                                     -1.28
...                                        ...
29563                                     0.00
29564                                     0.00
29565                                     0.00
29566                                     0.00
29567                                     0.00

       WEEE_2RM_mechRec1Smelter_other  ...  WEEE_2RM_chem2Smelter_other  \
8022                              NaN  ...                          NaN
8023                             0.00  ...                          NaN
8024                             0.00  ...                          NaN
8025                             0.00  ...                          NaN
8026                             0.00  ...                          NaN
...                               ...  ...                          ...
29563                           -2.62  ...                          NaN
29564                           -1.04  ...                          NaN
29565                           -1.04  ...                          NaN
29566                           -3.71  ...                          NaN
29567                           -3.71  ...                          NaN

       WEEE_generatedComplementaryMetalScrap  WEEE_collected  \
8022                             -355,718.92     -948,583.79
8023                               -3,052.13       -8,139.01
8024                                 -207.46         -553.23
8025                                  -30.66          -81.75
8026                                   -0.55           -1.46
...                                      ...             ...
29563                                   0.00            0.00
29564                                   0.00            0.00
29565                                   0.00            0.00
29566                                   0.00            0.00
29567                                   0.00            0.00

       WEEE_generatedDedicated  WEEE_mechRec2_thermal  WEEE_mechRec1_mechRec2  \
8022              1,693,899.63                    NaN                     NaN
8023                 14,533.95                    NaN                    0.00
8024                    987.90                    NaN                    0.00
8025                    145.98                    NaN                    0.00
8026                      2.60                    NaN                    0.00
...                        ...                    ...                     ...
29563                     0.00                    NaN                   -2.99
29564                     0.00                    NaN                   -1.18
29565                     0.00                    NaN                   -1.18
29566                     0.00                    NaN                   -4.23
29567                     0.00                    NaN                   -4.23

       WEEE_chem_thermal  WEEE_categ_mechRec2  WEEE_categ_mechRec1  \
8022                 NaN                 0.00                 0.00
8023                 NaN                 0.00                 0.00
8024                 NaN                 0.00                 0.00
8025                 NaN                 0.00                 0.00
8026                 NaN                 0.00                 0.00
...                  ...                  ...                  ...
29563                NaN                 0.00                 5.24
29564                NaN                 0.00                 2.07
29565                NaN                 0.00                 2.07
29566                NaN                 0.00                 7.42
29567                NaN                 0.00                 7.42

       mass_balance
8022  -1,507,570.67
8023     -12,935.21
8024        -879.23
8025        -129.92
8026          -2.32
...             ...
29563         -0.37
29564         -0.14
29565         -0.14
29566         -0.52
29567         -0.52

[8107 rows x 25 columns]

                                    flow    layer         key       data
0    WEEE_generatedComplementaryExported  product   WEEE_Cat1 135,511.97
1    WEEE_generatedComplementaryExported  product   WEEE_Cat2 123,339.65
2    WEEE_generatedComplementaryExported  product   WEEE_Cat3  20,937.23
3    WEEE_generatedComplementaryExported  product  WEEE_Cat4a 418,518.52
4    WEEE_generatedComplementaryExported  product  WEEE_Cat4b  48,473.30
..                                   ...      ...         ...        ...
254                  WEEE_categ_mechRec1  element          Pd   4,137.83
255                  WEEE_categ_mechRec1  element          Sc   7,528.58
256                  WEEE_categ_mechRec1  element          Sm  30,229.69
257                  WEEE_categ_mechRec1  element          Sr   1,269.21
258                  WEEE_categ_mechRec1  element          Zr  25,075.16

[1709 rows x 4 columns]

In [49]:
model.solve(aggregate=False, pivot=True).fillna("")

          product            component                   material element  \
8022    WEEE_Cat1                  NaN                        NaN     NaN
8023    WEEE_Cat1  ComponentShadowWEEE                        NaN     NaN
8024    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys     NaN
8025    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      Ag
8026    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      As
...           ...                  ...                        ...     ...
29563  WEEE_Cat4b   passiveJunctionBox              CuAndCuAlloys      Zr
29564  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials     NaN
29565  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials      Ag
29566  WEEE_Cat4b   passiveJunctionBox                   plastics     NaN
29567  WEEE_Cat4b   passiveJunctionBox                   plastics      Ag

              process  WEEE_generatedComplementaryExported  \
8022   WEEE_generated                          -135,511.97
8023   WEEE_generated                            -1,162.72
8024   WEEE_generated                               -79.03
8025   WEEE_generated                               -11.68
8026   WEEE_generated                                -0.21
...               ...                                  ...
29563     dismantling                                 0.00
29564     dismantling                                 0.00
29565     dismantling                                 0.00
29566     dismantling                                 0.00
29567     dismantling                                 0.00

       WEEE_2RM_thermal2Smelter_other  WEEE_mechRec2_chem  \
8022                              NaN                 NaN
8023                              NaN                 NaN
8024                              NaN                 NaN
8025                              NaN                 NaN
8026                              NaN                 NaN
...                               ...                 ...
29563                             NaN                 NaN
29564                             NaN                 NaN
29565                             NaN                 NaN
29566                             NaN                 NaN
29567                             NaN                 NaN

       WEEE_generatedComplementaryUndocumented  \
8022                               -830,010.82
8023                                 -7,121.63
8024                                   -484.07
8025                                    -71.53
8026                                     -1.28
...                                        ...
29563                                     0.00
29564                                     0.00
29565                                     0.00
29566                                     0.00
29567                                     0.00

       WEEE_2RM_mechRec1Smelter_other  ...  WEEE_2RM_chem2Smelter_other  \
8022                              NaN  ...                          NaN
8023                             0.00  ...                          NaN
8024                             0.00  ...                          NaN
8025                             0.00  ...                          NaN
8026                             0.00  ...                          NaN
...                               ...  ...                          ...
29563                           -2.62  ...                          NaN
29564                           -1.04  ...                          NaN
29565                           -1.04  ...                          NaN
29566                           -3.71  ...                          NaN
29567                           -3.71  ...                          NaN

       WEEE_generatedComplementaryMetalScrap  WEEE_collected  \
8022                             -355,718.92     -948,583.79
8023                               -3,052.13       -8,139.01
8024                                 -207.46         -553.23
8025                                  -30.66          -81.75
8026                                   -0.55           -1.46
...                                      ...             ...
29563                                   0.00            0.00
29564                                   0.00            0.00
29565                                   0.00            0.00
29566                                   0.00            0.00
29567                                   0.00            0.00

       WEEE_generatedDedicated  WEEE_mechRec2_thermal  WEEE_mechRec1_mechRec2  \
8022              1,693,899.63                    NaN                     NaN
8023                 14,533.95                    NaN                    0.00
8024                    987.90                    NaN                    0.00
8025                    145.98                    NaN                    0.00
8026                      2.60                    NaN                    0.00
...                        ...                    ...                     ...
29563                     0.00                    NaN                   -2.99
29564                     0.00                    NaN                   -1.18
29565                     0.00                    NaN                   -1.18
29566                     0.00                    NaN                   -4.23
29567                     0.00                    NaN                   -4.23

       WEEE_chem_thermal  WEEE_categ_mechRec2  WEEE_categ_mechRec1  \
8022                 NaN                 0.00                 0.00
8023                 NaN                 0.00                 0.00
8024                 NaN                 0.00                 0.00
8025                 NaN                 0.00                 0.00
8026                 NaN                 0.00                 0.00
...                  ...                  ...                  ...
29563                NaN                 0.00                 5.24
29564                NaN                 0.00                 2.07
29565                NaN                 0.00                 2.07
29566                NaN                 0.00                 7.42
29567                NaN                 0.00                 7.42

       mass_balance
8022  -1,507,570.67
8023     -12,935.21
8024        -879.23
8025        -129.92
8026          -2.32
...             ...
29563         -0.37
29564         -0.14
29565         -0.14
29566         -0.52
29567         -0.52

[8107 rows x 25 columns]

flow,product,component,material,element,WEEE_generatedComplementaryExported,WEEE_2RM_thermal2Smelter_other,WEEE_mechRec2_chem,WEEE_generatedComplementaryUndocumented,WEEE_2RM_mechRec1Smelter_other,WEEE_generatedComplementaryMSW,...,WEEE_thermal_chem,WEEE_2RM_chem2Smelter_other,WEEE_generatedComplementaryMetalScrap,WEEE_collected,WEEE_generatedDedicated,WEEE_mechRec2_thermal,WEEE_mechRec1_mechRec2,WEEE_chem_thermal,WEEE_categ_mechRec2,WEEE_categ_mechRec1
0,WEEE_Cat1,,,,"135,511.97",,,"830,010.82",,"931,644.80",...,,,"355,718.92","948,583.79","1,693,899.63",,,,"464,806.06","322,518.49"
1,WEEE_Cat1,ComponentShadowWEEE,,,"1,162.72",,,"7,121.63","1,632.69","7,993.67",...,,,"3,052.13","8,139.01","14,533.95",,"1,328.29",,"3,988.12","2,767.26"
2,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,,79.03,,,484.07,110.98,543.35,...,,,207.46,553.23,987.90,,90.29,,271.08,188.10
3,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,Ag,11.68,,,71.53,16.40,80.29,...,,,30.66,81.75,145.98,,13.34,,40.06,27.79
4,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,As,0.21,,,1.28,0.29,1.43,...,,,0.55,1.46,2.60,,0.24,,0.71,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8017,WEEE_Cat6,wheel,polymerPA6GF30,Ag,43.45,,,191.18,,21.72,...,,,212.90,139.04,434.49,,,,79.25,23.64
8018,WEEE_Cat6,wheel,polymerPPTF20,,225.52,,,992.29,,112.76,...,,,"1,105.05",721.66,"2,255.20",,,,411.35,122.68
8019,WEEE_Cat6,wheel,polymerPPTF20,Ag,225.52,,,992.29,,112.76,...,,,"1,105.05",721.66,"2,255.20",,,,411.35,122.68
8020,WEEE_Cat6,wheel,polymerPPTF30,,209.66,,,922.52,,104.83,...,,,"1,027.35",670.92,"2,096.63",,,,382.43,114.06
8021,WEEE_Cat6,wheel,polymerPPTF30,Ag,209.66,,,922.52,,104.83,...,,,"1,027.35",670.92,"2,096.63",,,,382.43,114.06

In [16]:
model.solve(aggregate=False, pivot=False).fillna("")

    flow product component material element     data
0     F1      P1                            1,000.00
1     F1      P1        C1                    250.00
2     F1      P1        C1       M1           130.00
3     F1      P1        C1       M1      E1    91.00
4     F1      P1        C1       M1      E2    39.00
..   ...     ...       ...      ...     ...      ...
175   F8      P1        C3       M2      E2     0.40
176   F8      P2        C1       M1      E1     0.23
177   F8      P2        C1       M2      E2     0.09
178   F8      P2        C2       M1      E1     0.28
179   F8      P2        C2       M2      E2     0.07

[180 rows x 6 columns]

In [55]:
# ---------------------- TEST
cols = ["product", "component", "material", "element", "WEEE_generatedDedicated"]
TEST_REST = model.solve(aggregate=False, pivot=True).fillna("")[cols]
TEST_REST

          product            component                   material element  \
8022    WEEE_Cat1                  NaN                        NaN     NaN
8023    WEEE_Cat1  ComponentShadowWEEE                        NaN     NaN
8024    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys     NaN
8025    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      Ag
8026    WEEE_Cat1  ComponentShadowWEEE              AlAndAlAlloys      As
...           ...                  ...                        ...     ...
29563  WEEE_Cat4b   passiveJunctionBox              CuAndCuAlloys      Zr
29564  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials     NaN
29565  WEEE_Cat4b   passiveJunctionBox  otherOrUndefinedMaterials      Ag
29566  WEEE_Cat4b   passiveJunctionBox                   plastics     NaN
29567  WEEE_Cat4b   passiveJunctionBox                   plastics      Ag

              process  WEEE_generatedComplementaryExported  \
8022   WEEE_generated                          -135,511.97
8023   WEEE_generated                            -1,162.72
8024   WEEE_generated                               -79.03
8025   WEEE_generated                               -11.68
8026   WEEE_generated                                -0.21
...               ...                                  ...
29563     dismantling                                 0.00
29564     dismantling                                 0.00
29565     dismantling                                 0.00
29566     dismantling                                 0.00
29567     dismantling                                 0.00

       WEEE_2RM_thermal2Smelter_other  WEEE_mechRec2_chem  \
8022                              NaN                 NaN
8023                              NaN                 NaN
8024                              NaN                 NaN
8025                              NaN                 NaN
8026                              NaN                 NaN
...                               ...                 ...
29563                             NaN                 NaN
29564                             NaN                 NaN
29565                             NaN                 NaN
29566                             NaN                 NaN
29567                             NaN                 NaN

       WEEE_generatedComplementaryUndocumented  \
8022                               -830,010.82
8023                                 -7,121.63
8024                                   -484.07
8025                                    -71.53
8026                                     -1.28
...                                        ...
29563                                     0.00
29564                                     0.00
29565                                     0.00
29566                                     0.00
29567                                     0.00

       WEEE_2RM_mechRec1Smelter_other  ...  WEEE_2RM_chem2Smelter_other  \
8022                              NaN  ...                          NaN
8023                             0.00  ...                          NaN
8024                             0.00  ...                          NaN
8025                             0.00  ...                          NaN
8026                             0.00  ...                          NaN
...                               ...  ...                          ...
29563                           -2.62  ...                          NaN
29564                           -1.04  ...                          NaN
29565                           -1.04  ...                          NaN
29566                           -3.71  ...                          NaN
29567                           -3.71  ...                          NaN

       WEEE_generatedComplementaryMetalScrap  WEEE_collected  \
8022                             -355,718.92     -948,583.79
8023                               -3,052.13       -8,139.01
8024                                 -207.46         -553.23
8025                                  -30.66          -81.75
8026                                   -0.55           -1.46
...                                      ...             ...
29563                                   0.00            0.00
29564                                   0.00            0.00
29565                                   0.00            0.00
29566                                   0.00            0.00
29567                                   0.00            0.00

       WEEE_generatedDedicated  WEEE_mechRec2_thermal  WEEE_mechRec1_mechRec2  \
8022              1,693,899.63                    NaN                     NaN
8023                 14,533.95                    NaN                    0.00
8024                    987.90                    NaN                    0.00
8025                    145.98                    NaN                    0.00
8026                      2.60                    NaN                    0.00
...                        ...                    ...                     ...
29563                     0.00                    NaN                   -2.99
29564                     0.00                    NaN                   -1.18
29565                     0.00                    NaN                   -1.18
29566                     0.00                    NaN                   -4.23
29567                     0.00                    NaN                   -4.23

       WEEE_chem_thermal  WEEE_categ_mechRec2  WEEE_categ_mechRec1  \
8022                 NaN                 0.00                 0.00
8023                 NaN                 0.00                 0.00
8024                 NaN                 0.00                 0.00
8025                 NaN                 0.00                 0.00
8026                 NaN                 0.00                 0.00
...                  ...                  ...                  ...
29563                NaN                 0.00                 5.24
29564                NaN                 0.00                 2.07
29565                NaN                 0.00                 2.07
29566                NaN                 0.00                 7.42
29567                NaN                 0.00                 7.42

       mass_balance
8022  -1,507,570.67
8023     -12,935.21
8024        -879.23
8025        -129.92
8026          -2.32
...             ...
29563         -0.37
29564         -0.14
29565         -0.14
29566         -0.52
29567         -0.52

[8107 rows x 25 columns]

flow,product,component,material,element,WEEE_generatedDedicated
0,WEEE_Cat1,,,,"1,693,899.63"
1,WEEE_Cat1,ComponentShadowWEEE,,,"14,533.95"
2,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,,987.90
3,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,Ag,145.98
4,WEEE_Cat1,ComponentShadowWEEE,AlAndAlAlloys,As,2.60
...,...,...,...,...,...
8017,WEEE_Cat6,wheel,polymerPA6GF30,Ag,434.49
8018,WEEE_Cat6,wheel,polymerPPTF20,,"2,255.20"
8019,WEEE_Cat6,wheel,polymerPPTF20,Ag,"2,255.20"
8020,WEEE_Cat6,wheel,polymerPPTF30,,"2,096.63"
8021,WEEE_Cat6,wheel,polymerPPTF30,Ag,"2,096.63"

In [68]:
model.dims

(19, 8, 83, 31, 18)

In [71]:
counter = TEST_REST[cols[:-1]].apply(np.unique)

print(np.prod(counter.apply(len)))
print(counter.apply(len))

324198
flow
product       7
component    83
material     31
element      18
dtype: int64

In [77]:
temp = TEST_REST[TEST_REST["product"] == "WEEE_Cat3"]

counter = temp[cols[:-1]].apply(np.unique)

print(np.prod(counter.apply(len)))
print(counter.apply(len))

46314
flow
product       1
component    83
material     31
element      18
dtype: int64

---

# Performance

In [19]:
%%prun -l 20 -s cumulative

model = RecoveryModel(
    name=folder,
    metadata=metadata,
    composition=composition,
    inputs=inputs,
    tcs=tcs,
    layer_names=layer_names,
    save_intermediary_steps=False,
    save_duplicates=False,
)

         157609 function calls (154276 primitive calls) in 3.464 seconds

   Ordered by: cumulative time
   List reduced from 1444 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      2/1    0.000    0.000    3.465    3.465 {built-in method builtins.exec}
      2/1    0.000    0.000    3.465    3.465 <string>:1(<module>)
        5    0.000    0.000    2.314    0.463 base_events.py:1908(_run_once)
        1    0.018    0.018    1.171    1.171 recovery_model.py:37(__post_init__)
       61    0.002    0.000    0.982    0.016 managers.py:869(take)
       73    0.001    0.000    0.877    0.012 managers.py:623(reindex_indexer)
  280/253    0.001    0.000    0.872    0.003 take.py:59(take_nd)
      165    0.001    0.000    0.871    0.005 blocks.py:1287(take_nd)
      253    0.759    0.003    0.869    0.003 take.py:120(_take_nd_ndarray)
        1    0.020    0.020    0.822    0.822 recovery_model.py:219(read_tcs)
    97/66    0.001    0.000    0.545    0.008 indexing.py:1176(__getitem__)
        1    0.000    0.000    0.504    0.504 frame.py:6984(sort_values)
       59    0.000    0.000    0.502    0.009 generic.py:4139(_take_with_is_copy)
       59    0.001    0.000    0.502    0.009 generic.py:4024(take)
        2    0.099    0.050    0.343    0.172 sorting.py:369(nargsort)
        1    0.000    0.000    0.323    0.323 frame.py:7269(sort_index)
        1    0.000    0.000    0.323    0.323 generic.py:5287(sort_index)
       71    0.001    0.000    0.299    0.004 indexing.py:1397(_getitem_axis)
        4    0.286    0.071    0.288    0.072 frame.py:6815(duplicated)
       41    0.000    0.000    0.287    0.007 indexing.py:1205(_getbool_axis)

In [23]:
cProfile.run(
    "RecoveryModel(name=folder, metadata=metadata, composition=composition, inputs=inputs, tcs=tcs, layer_names=layer_names, save_intermediary_steps=False, save_duplicates=False)",
    "performance/RecoveryModel.pstats",
)

cProfile.run(
    "model.solve(aggregate=False, pivot=True)",
    "performance/Solver.pstats",
)

# # ! then go into results/performances/ and run the following commands
# # (-n 2 means cutoff at 2%)
# gprof2dot -f pstats -n 1 RecoveryModel.pstats | dot -Tpng -o RecoveryModel.png
# gprof2dot -f pstats -n 1 Solver.pstats | dot -Tpng -o Solver.png

In [24]:
cProfile.run(
    "RecoveryModel(name=folder, metadata=metadata, composition=composition, inputs=inputs, tcs=tcs, layer_names=layer_names, save_intermediary_steps=False, save_duplicates=False)",
    "performance/RecoveryModel.prof",
)

cProfile.run(
    "model.solve(aggregate=False, pivot=True)",
    "performance/Solver.prof",
)

# # ! then go into results/performances/ and run the following commands
# snakeviz RecoveryModel.prof
# snakeviz Solver.prof